site_name: pGenie Docs

site_url: https://pgenie.io/docs/

repo_url: https://github.com/pgenie-io/pgenie
repo_name: pgenie-io/pgenie

copyright: |
  &copy; 2026 Project of <a href="https://codemine.io">CodeMine Consulting</a>

extra:
  homepage: https://pgenie.io

theme:
  name: material
  logo: logo-icon.svg
  favicon: logo-icon.svg
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

  features:
    - content.code.copy
    - content.code.select
    - navigation.footer
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.tabs.sticky
    - toc.follow
    - content.footnote.tooltips

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - tables

nav:
  - Home: index.md
  - How It Works: how-it-works.md
  - Guides:
      - Installation:
          - guides/installation/index.md
          - macOS: guides/installation/macos.md
          - Linux: guides/installation/linux.md
          - Windows: guides/installation/windows.md
      - Writing Migrations: guides/writing-migrations.md
      - Writing Queries: guides/writing-queries.md
      - Configuring Generators: guides/configuring-generators.md
      - Generating Code: guides/generating-code.md
      - Managing Indexes: guides/managing-indexes.md
      - Using pGenie in CI/CD: guides/cicd.md
      - Implementing Custom Generators: guides/implementing-custom-generators.md
      - Integrating with Migration Tools:
          - guides/migration-tools/index.md
          - Flyway: guides/migration-tools/flyway.md
          - Liquibase: guides/migration-tools/liquibase.md
          - Sqitch: guides/migration-tools/sqitch.md
  - Reference:
      - Project Structure: reference/project-structure.md
      - Project File: reference/project-file.md
      - Query Signature File: reference/query-signature-file.md
      - Freeze File: reference/freeze-file.md
      - Codegens: reference/codegens.md
  - Tutorials:
      - Learn pGenie in Y Minutes: tutorials/learn-pgenie-in-y-minutes.md
  - Support: support.md
